export const data = [
    {
        'title':'Alignment',
        'classes' :[
            'slds-align_absolute-center'
        ]
    }
    ,{
        'title':'Borders',
        'classes':[
            'slds-border_top',
            'slds-border_right',
            'slds-border_bottom',
            'slds-border_left'
        ]
    }
    ,{
        'title':'Box',
        'classes':[
            'slds-box',
            'slds-box_small',
            'slds-box_x-small',
            'slds-box_xx-small'
        ]
    }
    ,{
        'title':'Floats',
        'classes':[
            'slds-clearfix',
            'slds-float_left',
            'slds-float_right',
            'slds-float_none'
        ]
    }
    ,{
        'title':'Grid',
        'classes':[
            'slds-gutters',
            'slds-col',
            'slds-size_1-of-3',
            'slds-size_2-of-3',
            'slds-size_1-of-12',
            'slds-size_1-of-6',
            'slds-gutters_x-small',
            'slds-gutters_small',
            'slds-gutters_medium',
            'slds-gutters_large',
            'slds-gutters_x-large',
            'slds-grid_pull-padded-medium',
            'slds-gutters_direct',
            'slds-wrap',
            'slds-order_1',
            'slds-order_2',
            'slds-order_3',
            'slds-grid_vertical',
            'slds-grid_reverse',
            'slds-grid_vertical-reverse',
            'slds-grid_align-center',
            'slds-grid_align-center',
            'slds-grid_align-space',
            'slds-grow-none',
            'slds-grid_align-spread',
            'slds-grid_align-end',
            '',
            '',
            '',
            '',
        ]
    }
]